language: ruby
before_install:
  - 'echo "gem: --no-ri --no-rdoc" > ~/.gemrc'
  - bundle --version
  - gem --version
bundler_args: --without development
cache: bundler

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
#  - ruby-head    # The latest Ruby, whatever version it happens to be.
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - 1.8.7

matrix:
  allow_failures:
    - rvm: rbx            # rbx has been problematic.
  include:
    - rvm: rbx
      gemfile: gemfiles/Gemfile.rbx
    - rvm: 2.1.3
      env: COVERAGE=true
  exclude:
    - rvm: rbx
      gemfile: Gemfile

# blacklist
branches:
  except:
    - develop
    - rt-site
    - gh-pages
